"""
DaDude - Models Package
"""
from .schemas import (
    DeviceStatus,
    ProbeStatus,
    Device,
    Probe,
    Alert,
    DeviceGroup,
    NetworkMap,
    DudeServerInfo,
    DeviceListResponse,
    ProbeListResponse,
    AlertListResponse,
    WebhookPayload,
    StatusResponse,
)

from .customer_schemas import (
    NetworkType,
    CredentialType,
    DeviceRole,
    ContractType,
    SLALevel,
    Customer,
    CustomerCreate,
    CustomerUpdate,
    CustomerListResponse,
    CustomerWithDetails,
    Network,
    NetworkCreate,
    NetworkUpdate,
    NetworkListResponse,
    Credential,
    CredentialCreate,
    CredentialUpdate,
    CredentialSafe,
    CredentialListResponse,
    DeviceAssignment,
    DeviceAssignmentCreate,
    DeviceAssignmentUpdate,
    DeviceAssignmentListResponse,
)

from .database import (
    Base,
    Customer as CustomerDB,
    Network as NetworkDB,
    Credential as CredentialDB,
    DeviceAssignment as DeviceAssignmentDB,
    AlertHistory,
    init_db,
    get_session,
)

from .inventory import (
    InventoryDevice,
    NetworkInterface,
    DiskInfo,
    InstalledSoftware,
    ServiceInfo,
    WindowsDetails,
    LinuxDetails,
    MikroTikDetails,
    NetworkDeviceDetails,
    NetwatchConfig,
    DudeAgent,
)

__all__ = [
    # Schemas base
    "DeviceStatus",
    "ProbeStatus",
    "Device",
    "Probe",
    "Alert",
    "DeviceGroup",
    "NetworkMap",
    "DudeServerInfo",
    "DeviceListResponse",
    "ProbeListResponse",
    "AlertListResponse",
    "WebhookPayload",
    "StatusResponse",
    # Customer schemas
    "NetworkType",
    "CredentialType",
    "DeviceRole",
    "ContractType",
    "SLALevel",
    "Customer",
    "CustomerCreate",
    "CustomerUpdate",
    "CustomerListResponse",
    "CustomerWithDetails",
    "Network",
    "NetworkCreate",
    "NetworkUpdate",
    "NetworkListResponse",
    "Credential",
    "CredentialCreate",
    "CredentialUpdate",
    "CredentialSafe",
    "CredentialListResponse",
    "DeviceAssignment",
    "DeviceAssignmentCreate",
    "DeviceAssignmentUpdate",
    "DeviceAssignmentListResponse",
    # Database
    "Base",
    "CustomerDB",
    "NetworkDB",
    "CredentialDB",
    "DeviceAssignmentDB",
    "AlertHistory",
    "init_db",
    "get_session",
    # Inventory
    "InventoryDevice",
    "NetworkInterface",
    "DiskInfo",
    "InstalledSoftware",
    "ServiceInfo",
    "WindowsDetails",
    "LinuxDetails",
    "MikroTikDetails",
    "NetworkDeviceDetails",
    "NetwatchConfig",
    "DudeAgent",
]
